### PR TITLE
Added Option atRoot

### PR DESCRIPTION
**Pull request by nucliweb**
* Added **option** `atRoot: true` to prevent the `@keyframes` can be nested in a ​**media queries**
* Added `.editorconfig` for maintain consistent coding styles

### CODE REVIEW

**Comment by nucliweb** [comment]
@zhouwenbin In my environment I have all test passed  o_O

**Comment by zhouwenbin** [comment]
@nucliweb thanks a lot

**Comment by zhouwenbin** [comment]
@nucliweb PostCSS 5.0 does not support node 0.10 https://github.com/webpack/css-loader/issues/144

**Comment by zhouwenbin** [comment]
@nucliweb this pr has some problem.https://github.com/zhouwenbin/postcss-animation/issues/5

**Pull request merged**
